import { MapPin, Upload } from 'lucide-react';
import { useState } from 'react';
import { useGeolocation } from '../../hooks/useGeolocation';
import { PRIORITIES, SERVICE_STATUSES } from '../../utils/constants';

const issueCategories = ['door', 'cabin', 'electrical', 'noise-vibration', 'display-controls', 'safety', 'other'];

export function ServiceRequestForm({ lifts = [], employees = [], initial, admin, customer, onSave, onCancel }) {
  const [form, setForm] = useState({ requestType: 'service', lift: '', title: '', description: '', priority: 'medium', issueCategory: 'other', status: 'open', assignedTechnician: '', siteAddress: initial?.siteLocation?.address || '', latitude: initial?.siteLocation?.latitude ?? '', longitude: initial?.siteLocation?.longitude ?? '', requestedMaintenanceDate: initial?.requestedMaintenanceDate?.slice(0, 10) || '', ...initial, dueDate: initial?.dueDate?.slice(0, 10) || '' });
  const [media, setMedia] = useState([]);
  const [saving, setSaving] = useState(false);
  const { getLocation, error: locationError } = useGeolocation();
  const change = (event) => {
    const { name, value } = event.target;
    setForm((current) => name === 'requestType' ? { ...current, requestType: value, priority: value === 'emergency' ? 'critical' : current.priority } : { ...current, [name]: value });
  };
  const useCurrentLocation = async () => { try { const point = await getLocation(); setForm((current) => ({ ...current, latitude: point.latitude, longitude: point.longitude })); } catch { return undefined; } };
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const { siteAddress, latitude, longitude, ...data } = form; const hasLocation = siteAddress || latitude !== '' || longitude !== ''; await onSave({ ...data, siteLocation: hasLocation ? { address: siteAddress, latitude: latitude === '' ? undefined : Number(latitude), longitude: longitude === '' ? undefined : Number(longitude) } : undefined }, media); } finally { setSaving(false); } };
  const needsLift = ['service', 'emergency', 'maintenance-reschedule'].includes(form.requestType);
  const asksForSite = customer && ['new-lift', 'general-query'].includes(form.requestType);
  return <form className="form-grid" onSubmit={submit}>
    {customer && <label>Request type<select name="requestType" value={form.requestType} onChange={change}><option value="service">Service request</option><option value="emergency">Emergency breakdown</option><option value="maintenance-reschedule">Reschedule maintenance</option><option value="new-lift">New lift enquiry</option><option value="general-query">General query</option></select></label>}
    {needsLift && <label>Lift<select required name="lift" value={form.lift?._id || form.lift} onChange={change}><option value="">Select lift</option>{lifts.map((lift) => <option value={lift._id} key={lift._id}>{lift.code} — {lift.name}</option>)}</select></label>}
    <label>Priority<select name="priority" value={form.priority} disabled={form.requestType === 'emergency'} onChange={change}>{PRIORITIES.map((item) => <option key={item}>{item}</option>)}</select></label>
    {customer && <label>Issue category<select name="issueCategory" value={form.issueCategory} onChange={change}>{issueCategories.map((item) => <option key={item}>{item.replaceAll('-', ' ')}</option>)}</select></label>}
    <label className="full">{form.requestType === 'new-lift' ? 'Project title' : form.requestType === 'general-query' ? 'Query subject' : 'Issue title'}<input required name="title" value={form.title} onChange={change} /></label><label className="full">{form.requestType === 'new-lift' ? 'Site and requirements' : 'Description'}<textarea required name="description" value={form.description} onChange={change} rows="4" /></label>
    {form.requestType === 'maintenance-reschedule' && <label>Requested maintenance date<input required type="date" name="requestedMaintenanceDate" value={form.requestedMaintenanceDate} onChange={change} /></label>}
    {asksForSite && <><label className="full">Installation / enquiry address<input name="siteAddress" value={form.siteAddress} onChange={change} placeholder="Building, street, city" /></label><label>Latitude<input type="number" step="any" name="latitude" value={form.latitude} onChange={change} /></label><label>Longitude<input type="number" step="any" name="longitude" value={form.longitude} onChange={change} /></label><div className="form-actions compact-location-action"><button type="button" className="secondary" onClick={useCurrentLocation}><MapPin size={16} /> Use my location</button></div>{locationError && <p className="form-help error-text">{locationError}</p>}</>}
    {customer && <label className="full">Issue photos or videos <span className="file-input"><Upload size={15} /><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" multiple onChange={(event) => setMedia(Array.from(event.target.files || []).slice(0, 3))} />{media.length ? `${media.length} file${media.length > 1 ? 's' : ''} selected` : 'Add up to 3 files (5 MB each)'}</span></label>}
    {admin && <><label>Assign technician<select name="assignedTechnician" value={form.assignedTechnician?._id || form.assignedTechnician || ''} onChange={change}><option value="">Unassigned</option>{employees.map((employee) => <option value={employee._id} key={employee._id}>{employee.user?.name} ({employee.employeeCode})</option>)}</select></label><label>Status<select name="status" value={form.status} onChange={change}>{SERVICE_STATUSES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Technician arrival<select name="technicianArrivalStatus" value={form.technicianArrivalStatus || 'not-assigned'} onChange={change}>{['not-assigned', 'scheduled', 'en-route', 'arrived', 'on-site'].map((item) => <option key={item}>{item.replaceAll('-', ' ')}</option>)}</select></label><label>Arrival ETA<input type="datetime-local" name="technicianArrivalEta" value={form.technicianArrivalEta?.slice(0, 16) || ''} onChange={change} /></label><label>Estimated completion<input type="datetime-local" name="estimatedCompletion" value={form.estimatedCompletion?.slice(0, 16) || ''} onChange={change} /></label><label className="full">Parts replaced<textarea name="partsReplaced" value={form.partsReplaced || ''} onChange={change} rows="2" placeholder="Parts, quantities, and notes" /></label></>}
    {!customer && <label>Due date<input type="date" name="dueDate" value={form.dueDate} onChange={change} /></label>}<div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button disabled={saving}>{saving ? 'Saving…' : customer ? 'Send request' : 'Save request'}</button></div>
  </form>;
}
