import { useState } from 'react';
import { Camera, MapPin } from 'lucide-react';
import { MapContainer, Marker, TileLayer, useMapEvents } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { RouteMap } from '../../components/maps/RouteMap';
import { ServiceLocationMap } from '../../components/maps/ServiceLocationMap';
import { Loader } from '../../components/common/Loader';
import { getServiceRequests } from '../../services/serviceRequestService';
import { logLocation } from '../../services/locationService';
import { useFetch } from '../../hooks/useFetch';
import { useGeolocation } from '../../hooks/useGeolocation';

function LocationPicker({ onSelect }) { useMapEvents({ click: (event) => onSelect({ latitude: event.latlng.lat, longitude: event.latlng.lng, accuracy: 0 }) }); return null; }

export default function MyRoute() { const jobs = useFetch(getServiceRequests, []); const { getLocation } = useGeolocation(); const [message, setMessage] = useState(''); const [selected, setSelected] = useState(null); const [photo, setPhoto] = useState(null); const [busy, setBusy] = useState(false); const sendLocation = async () => { setBusy(true); setMessage(''); try { const location = await getLocation(); setSelected(location); await logLocation(location, photo); setMessage('Your current location and photo were shared with operations.'); } catch (e) { setMessage(e.message); } finally { setBusy(false); } }; const shareSelected = async (event) => { event.preventDefault(); if (!selected) return setMessage('Click the map to select a technician location first.'); setBusy(true); setMessage(''); try { await logLocation(selected, photo); setMessage('The selected location and photo were shared with operations.'); } catch (e) { setMessage(e.message); } finally { setBusy(false); } }; const active = jobs.data.filter((job) => !['resolved', 'closed'].includes(job.status)); const center = selected ? [selected.latitude, selected.longitude] : [20.5937, 78.9629]; return <><div className="page-heading action-heading"><div><span className="eyebrow">Today’s route</span><h1>My route</h1><p>Click the map to choose your position, optionally attach a site photo, and share both with operations.</p></div><button onClick={sendLocation} disabled={busy}><MapPin size={17} />{busy ? 'Sharing...' : 'Use current location'}</button></div><form className="location-capture" onSubmit={shareSelected}><MapContainer className="location-picker" center={center} zoom={selected ? 13 : 5} scrollWheelZoom><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><LocationPicker onSelect={setSelected} />{selected && <Marker position={[selected.latitude, selected.longitude]} />}</MapContainer><div className="location-capture-controls"><div><strong>{selected ? 'Location selected' : 'Select a location on the map'}</strong><p>{selected ? `${selected.latitude.toFixed(5)}, ${selected.longitude.toFixed(5)}` : 'Click anywhere on the map to place the technician marker.'}</p></div><label className="photo-picker"><Camera size={17} />{photo ? photo.name : 'Attach location photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setPhoto(event.target.files?.[0] || null)} /></label><button type="submit" disabled={busy || !selected}>Share location and photo</button></div></form>{message && <div className="alert">{message}</div>}{jobs.loading ? <Loader /> : <><RouteMap jobs={active} /><div className="route-list">{active.map((job) => <article key={job._id}><h3>{job.lift?.code} — {job.title}</h3><ServiceLocationMap request={job} /></article>)}{!active.length && <p className="empty-state">No active stops on your route.</p>}</div></>}</>; }

