import { Calculator } from 'lucide-react';
import { useMemo, useState } from 'react';
import { ExpenseTable } from '../../components/expenses/ExpenseTable';
import { Loader } from '../../components/common/Loader';
import { getExpenses, updateExpense } from '../../services/expenseService';
import { useFetch } from '../../hooks/useFetch';

export default function ExpenseOverview() { const { data, loading, error, reload } = useFetch(getExpenses, []); const [notice, setNotice] = useState(''); const [showTotal, setShowTotal] = useState(false); const groupedExpenses = useMemo(() => Object.values(data.reduce((groups, expense) => { const employeeId = expense.employee?._id || 'unassigned'; if (!groups[employeeId]) groups[employeeId] = { name: expense.employee?.user?.name || 'Unassigned employee', expenses: [] }; groups[employeeId].expenses.push(expense); return groups; }, {})), [data]); const totalExpense = data.reduce((total, expense) => total + Number(expense.amount || 0), 0); const review = async (expense) => { const next = expense.status === 'pending' ? 'approved' : expense.status === 'approved' ? 'rejected' : 'approved'; try { await updateExpense(expense._id, { status: next }); setNotice(`Expense marked ${next}. Click a status pill to cycle its review state.`); reload(); } catch (e) { setNotice(e.message); } }; return <><div className="page-heading"><div><span className="eyebrow">Reimbursements</span><h1>Expense overview</h1><p>Review technician claims. Each employee is shown separately.</p></div><button onClick={() => setShowTotal((visible) => !visible)}><Calculator size={17} />{showTotal ? 'Hide total' : 'Calculate total'}</button></div>{showTotal && <div className="expense-total"><span>Total submitted expenses</span><strong>₹{totalExpense.toLocaleString('en-IN')}</strong><small>{data.length} claim{data.length === 1 ? '' : 's'} across {groupedExpenses.length} employee{groupedExpenses.length === 1 ? '' : 's'}</small></div>}{notice && <div className="alert">{notice}</div>}{error && <div className="alert error">{error}</div>}{loading ? <Loader /> : <div className="expense-groups">{groupedExpenses.map((group) => <section className="expense-group" key={group.name}><div className="section-title"><h2>{group.name}</h2><span>₹{group.expenses.reduce((total, expense) => total + Number(expense.amount || 0), 0).toLocaleString('en-IN')} total</span></div><ExpenseTable expenses={group.expenses} onReview={review} /></section>)}{!groupedExpenses.length && <ExpenseTable expenses={data} onReview={review} />}</div>}</>; }

