import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import { LiftCard } from '../../components/lifts/LiftCard';
import { LiftForm } from '../../components/lifts/LiftForm';
import { Loader } from '../../components/common/Loader';
import { createLift, getLifts, removeLift, updateLift } from '../../services/liftService';
import { getChatContacts } from '../../services/chatService';
import { useFetch } from '../../hooks/useFetch';

export default function ManageLifts() { const { data: lifts, loading, error, reload } = useFetch(getLifts, []); const [editing, setEditing] = useState(null); const [customers, setCustomers] = useState([]); const [notice, setNotice] = useState(''); useEffect(() => { getChatContacts().then((users) => setCustomers(users.filter((item) => item.role === 'customer'))).catch(() => {}); }, []); const save = async (data) => { try { await (editing?._id ? updateLift(editing._id, data) : createLift(data)); setEditing(null); setNotice('Lift saved successfully.'); reload(); } catch (reason) { setNotice(reason.message); } }; const remove = async (lift) => { if (!window.confirm(`Remove ${lift.name}? Historical service records will be preserved.`)) return; try { await removeLift(lift._id); setNotice('Lift removed successfully.'); reload(); } catch (reason) { setNotice(reason.message); } }; return <><div className="page-heading action-heading"><div><span className="eyebrow">Asset registry</span><h1>Manage lifts</h1><p>Track condition, next service, and each installation’s details.</p></div><button onClick={() => setEditing({})}><Plus size={18} /> Add lift</button></div>{notice && <div className="alert">{notice}</div>}{editing && <section className="form-card"><div className="section-title"><h2>{editing._id ? 'Edit lift' : 'New lift'}</h2></div><LiftForm initial={editing} customers={customers} onSave={save} onCancel={() => setEditing(null)} /></section>}{error && <div className="alert error">{error}</div>}{loading ? <Loader /> : <div className="card-grid lifts-grid">{lifts.map((lift) => <LiftCard key={lift._id} lift={lift} onEdit={setEditing} onRemove={remove} />)}{!lifts.length && <p className="empty-state">Add the first lift to begin your register.</p>}</div>}</>; }
